#!/usr/bin/env bash
#
# install-index-hooks.sh — Install pre-push hooks across all Interverse subprojects
# that auto-refresh the solution doc index when solution docs are being pushed.
#
# Usage:
#   bash scripts/install-index-hooks.sh
#
# Installs a pre-push hook in every .git directory under apps/, os/, core/,
# interverse/, and the root. The hook checks if any docs/solutions/*.md files are in the
# push, and if so, runs the interlearn indexer.

set -euo pipefail

INTERVERSE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INDEXER="$INTERVERSE_ROOT/interverse/interlearn/scripts/index-solutions.sh"

if [ ! -x "$INDEXER" ]; then
    echo "Error: indexer not found at $INDEXER" >&2
    exit 1
fi

HOOK_CONTENT='#!/usr/bin/env bash
# Auto-generated by interlearn — refreshes cross-repo solution doc index on push.
# Runs only when docs/solutions/*.md files are included in the push.

INTERVERSE_ROOT="'"$INTERVERSE_ROOT"'"
INDEXER="$INTERVERSE_ROOT/interverse/interlearn/scripts/index-solutions.sh"

# Check if any solution docs are in the commits being pushed
while read -r local_ref local_sha remote_ref remote_sha; do
    if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
        continue  # Branch deletion
    fi
    if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
        range="$local_sha"
    else
        range="$remote_sha..$local_sha"
    fi
    if git diff --name-only "$range" 2>/dev/null | grep -q "docs/solutions/.*\.md$"; then
        echo "[interlearn] Solution docs changed — refreshing index..."
        bash "$INDEXER" "$INTERVERSE_ROOT" 2>/dev/null || true
        # Stage the updated index files if we are in the root repo
        if [ "$(git rev-parse --show-toplevel 2>/dev/null)" = "$INTERVERSE_ROOT" ]; then
            git add "$INTERVERSE_ROOT/docs/solutions/INDEX.md" "$INTERVERSE_ROOT/docs/solutions/index.json" 2>/dev/null || true
        fi
        break
    fi
done

exit 0
'

installed=0

# Find all .git directories (not inside .git itself)
while IFS= read -r gitdir; do
    hookdir="$gitdir/hooks"
    hookfile="$hookdir/pre-push"

    mkdir -p "$hookdir"

    if [ -f "$hookfile" ]; then
        # Check if our hook is already installed
        if grep -q "interlearn" "$hookfile" 2>/dev/null; then
            echo "  skip: $gitdir (already installed)"
            continue
        fi
        # Append to existing hook
        echo "" >> "$hookfile"
        echo "$HOOK_CONTENT" >> "$hookfile"
        echo "  append: $gitdir"
    else
        echo "$HOOK_CONTENT" > "$hookfile"
        chmod +x "$hookfile"
        echo "  install: $gitdir"
    fi
    installed=$((installed + 1))
done < <(find "$INTERVERSE_ROOT" -maxdepth 4 -name '.git' -type d 2>/dev/null | sort)

echo ""
echo "Installed pre-push hooks in $installed repos."
echo "Index will auto-refresh when docs/solutions/*.md files are pushed."
